=begin
#FriendlyScore Public API

#Public API for communication with FriendlyScore

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for FriendlyscoreClient::AuthAndRegistrationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AuthAndRegistrationApi' do
  before do
    # run before each test
    @instance = FriendlyscoreClient::AuthAndRegistrationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthAndRegistrationApi' do
    it 'should create an instance of AuthAndRegistrationApi' do
      expect(@instance).to be_instance_of(FriendlyscoreClient::AuthAndRegistrationApi)
    end
  end

  # unit tests for oauth_v2_token_post
  # Returns OAuth 2.0 token
  # @param [Hash] opts the optional parameters
  # @option opts [OAuthTokenRequestType] :oauth_token_request OAuth token request data
  # @return [Token]
  describe 'oauth_v2_token_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
