=begin
#FriendlyScore Public API

#Public API for communication with FriendlyScore

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for FriendlyscoreClient::ReportsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReportsApi' do
  before do
    # run before each test
    @instance = FriendlyscoreClient::ReportsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReportsApi' do
    it 'should create an instance of ReportsApi' do
      expect(@instance).to be_instance_of(FriendlyscoreClient::ReportsApi)
    end
  end

  # unit tests for public_version_customers_customer_id_forecasts_forecast_id_get
  # Get the the forecasts for customer
  # @param customer_id Customer ID
  # @param forecast_id ID of the forecast. Should be &#x60;current_personal&#x60; or &#x60;current_business&#x60;. &#x60;current&#x60; is now deprecated (works as &#x60;current_personal&#x60;).
  # @param version 
  # @param [Hash] opts the optional parameters
  # @return [Forecast]
  describe 'public_version_customers_customer_id_forecasts_forecast_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_version_customers_customer_id_insights_current_business_get
  # Get the insights for customer&#39;s business accounts
  # @param customer_id Customer ID
  # @param version 
  # @param [Hash] opts the optional parameters
  # @return [BusinessInsights]
  describe 'public_version_customers_customer_id_insights_current_business_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_version_customers_customer_id_insights_current_personal_get
  # Get the insights for customer&#39;s personal accounts
  # @param customer_id Customer ID
  # @param version 
  # @param [Hash] opts the optional parameters
  # @return [Insights]
  describe 'public_version_customers_customer_id_insights_current_personal_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
