=begin
#FriendlyScore Public API

#Public API for communication with FriendlyScore

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for FriendlyscoreClient::UsersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UsersApi' do
  before do
    # run before each test
    @instance = FriendlyscoreClient::UsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersApi' do
    it 'should create an instance of UsersApi' do
      expect(@instance).to be_instance_of(FriendlyscoreClient::UsersApi)
    end
  end

  # unit tests for public_version_customers_get
  # Returns the list of users. Can be used for seeking users.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :by_user_reference Filter by user identifier from **your** database
  # @return [UserCollection]
  describe 'public_version_customers_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_version_customers_post
  # Creates a new \&quot;empty\&quot; user.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [UserReferenceWithEntityType] :user_data Data to insert
  # @return [User]
  describe 'public_version_customers_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
