=begin
#FriendlyScore Public API

#Public API for communication with FriendlyScore

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'

# Unit tests for FriendlyscoreClient::UtilApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UtilApi' do
  before do
    # run before each test
    @instance = FriendlyscoreClient::UtilApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UtilApi' do
    it 'should create an instance of UtilApi' do
      expect(@instance).to be_instance_of(FriendlyscoreClient::UtilApi)
    end
  end

  # unit tests for public_version_customers_customer_id_data_processing_statuses_dtn_slug_get
  # Get the current status of a certain data processing request.
  # @param customer_id Customer ID
  # @param dtn_slug Data Processing Request slug
  # @param version 
  # @param [Hash] opts the optional parameters
  # @return [DtnDataProcessingSummary]
  describe 'public_version_customers_customer_id_data_processing_statuses_dtn_slug_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_version_customers_customer_id_data_processing_statuses_get
  # Get the current status of a all data processing requests for current user.
  # @param customer_id Customer ID
  # @param version 
  # @param [Hash] opts the optional parameters
  # @return [DtnDataProcessingSummaryCollection]
  describe 'public_version_customers_customer_id_data_processing_statuses_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_version_customers_customer_id_report_readiness_statuses_get
  # Get the current readiness status for all reports for current user.
  # @param customer_id Customer ID
  # @param version 
  # @param [Hash] opts the optional parameters
  # @return [ReportReadinessStatusCollection]
  describe 'public_version_customers_customer_id_report_readiness_statuses_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for public_version_customers_customer_id_report_readiness_statuses_report_name_get
  # Get the current readiness status for a certain report.
  # @param customer_id Customer ID
  # @param report_name Name of the report (e.g. &#x60;insights&#x60; or &#x60;forecast&#x60;)
  # @param version 
  # @param [Hash] opts the optional parameters
  # @return [ReportReadinessStatus]
  describe 'public_version_customers_customer_id_report_readiness_statuses_report_name_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
