=begin
#FriendlyScore Public API

#Public API for communication with FriendlyScore

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FriendlyscoreClient::CategoryMetadata
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CategoryMetadata' do
  before do
    # run before each test
    @instance = FriendlyscoreClient::CategoryMetadata.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CategoryMetadata' do
    it 'should create an instance of CategoryMetadata' do
      expect(@instance).to be_instance_of(FriendlyscoreClient::CategoryMetadata)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "income_expenditure"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["income", "expenditure"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.income_expenditure = value }.not_to raise_error
      # end
    end
  end

end
