=begin
#FriendlyScore Public API

#Public API for communication with FriendlyScore

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FriendlyscoreClient::DtnDataProcessingSummary
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DtnDataProcessingSummary' do
  before do
    # run before each test
    @instance = FriendlyscoreClient::DtnDataProcessingSummary.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DtnDataProcessingSummary' do
    it 'should create an instance of DtnDataProcessingSummary' do
      expect(@instance).to be_instance_of(FriendlyscoreClient::DtnDataProcessingSummary)
    end
  end
  describe 'test attribute "updated_at"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "processing_status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["failed", "in_progress", "finished"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.processing_status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "dtn_slug"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
