=begin
#FriendlyScore Public API

#Public API for communication with FriendlyScore

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FriendlyscoreClient::ExpenditureCategoryData
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExpenditureCategoryData' do
  before do
    # run before each test
    @instance = FriendlyscoreClient::ExpenditureCategoryData.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExpenditureCategoryData' do
    it 'should create an instance of ExpenditureCategoryData' do
      expect(@instance).to be_instance_of(FriendlyscoreClient::ExpenditureCategoryData)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "fixed_flexible"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["fixed", "flexible"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.fixed_flexible = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "monthly_amounts"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
