=begin
#FriendlyScore Public API

#Public API for communication with FriendlyScore

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FriendlyscoreClient::FinancialCredibilityScore
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FinancialCredibilityScore' do
  before do
    # run before each test
    @instance = FriendlyscoreClient::FinancialCredibilityScore.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FinancialCredibilityScore' do
    it 'should create an instance of FinancialCredibilityScore' do
      expect(@instance).to be_instance_of(FriendlyscoreClient::FinancialCredibilityScore)
    end
  end
  describe 'test attribute "generic"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "custom"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
