=begin
#FriendlyScore Public API

#Public API for communication with FriendlyScore

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.17

=end

# Common files
require 'friendlyscore_ruby/api_client'
require 'friendlyscore_ruby/api_error'
require 'friendlyscore_ruby/version'
require 'friendlyscore_ruby/configuration'

# Models
require 'friendlyscore_ruby/models/account'
require 'friendlyscore_ruby/models/account2'
require 'friendlyscore_ruby/models/account3'
require 'friendlyscore_ruby/models/account_collection'
require 'friendlyscore_ruby/models/account_input_collection'
require 'friendlyscore_ruby/models/amount_stat'
require 'friendlyscore_ruby/models/balance'
require 'friendlyscore_ruby/models/balance2'
require 'friendlyscore_ruby/models/balance_collection'
require 'friendlyscore_ruby/models/balance_forecast_data'
require 'friendlyscore_ruby/models/balance_input_collection'
require 'friendlyscore_ruby/models/bank'
require 'friendlyscore_ruby/models/bank_collection'
require 'friendlyscore_ruby/models/bank_with_consents'
require 'friendlyscore_ruby/models/bank_with_consents_collection'
require 'friendlyscore_ruby/models/base_balance'
require 'friendlyscore_ruby/models/base_balance2'
require 'friendlyscore_ruby/models/business_employment_data'
require 'friendlyscore_ruby/models/business_financial_markers_data'
require 'friendlyscore_ruby/models/business_insights'
require 'friendlyscore_ruby/models/category_metadata'
require 'friendlyscore_ruby/models/category_pattern'
require 'friendlyscore_ruby/models/consent_data'
require 'friendlyscore_ruby/models/consent_data2'
require 'friendlyscore_ruby/models/cummulative_stat_data_point'
require 'friendlyscore_ruby/models/customer_invitation'
require 'friendlyscore_ruby/models/customer_invitation_collection'
require 'friendlyscore_ruby/models/customer_invitation_collection__links'
require 'friendlyscore_ruby/models/customer_invitation_collection__links_self'
require 'friendlyscore_ruby/models/customer_invitation_type'
require 'friendlyscore_ruby/models/dtn_data_processing_summary'
require 'friendlyscore_ruby/models/dtn_data_processing_summary2'
require 'friendlyscore_ruby/models/dtn_data_processing_summary_collection'
require 'friendlyscore_ruby/models/employment_data'
require 'friendlyscore_ruby/models/expenditure_category_data'
require 'friendlyscore_ruby/models/expenditure_data'
require 'friendlyscore_ruby/models/expense_proportion'
require 'friendlyscore_ruby/models/financial_credibility_score'
require 'friendlyscore_ruby/models/financial_forecast'
require 'friendlyscore_ruby/models/financial_forecast_bank'
require 'friendlyscore_ruby/models/financial_markers_data'
require 'friendlyscore_ruby/models/financial_markers_data_summary_averages'
require 'friendlyscore_ruby/models/financial_patterns'
require 'friendlyscore_ruby/models/forecast'
require 'friendlyscore_ruby/models/historical_amount'
require 'friendlyscore_ruby/models/historical_amount2'
require 'friendlyscore_ruby/models/historical_cummulative_stat'
require 'friendlyscore_ruby/models/income_category_data'
require 'friendlyscore_ruby/models/income_data'
require 'friendlyscore_ruby/models/income_proportion'
require 'friendlyscore_ruby/models/insights'
require 'friendlyscore_ruby/models/o_auth_token_request_type'
require 'friendlyscore_ruby/models/reason_code'
require 'friendlyscore_ruby/models/recurrence'
require 'friendlyscore_ruby/models/report_readiness_status'
require 'friendlyscore_ruby/models/report_readiness_status2'
require 'friendlyscore_ruby/models/report_readiness_status_collection'
require 'friendlyscore_ruby/models/salary_expectation'
require 'friendlyscore_ruby/models/score'
require 'friendlyscore_ruby/models/score_with_codes'
require 'friendlyscore_ruby/models/score_with_days'
require 'friendlyscore_ruby/models/token'
require 'friendlyscore_ruby/models/transaction'
require 'friendlyscore_ruby/models/transaction2'
require 'friendlyscore_ruby/models/transaction_collection'
require 'friendlyscore_ruby/models/transaction_input_collection'
require 'friendlyscore_ruby/models/transactions_category_patch'
require 'friendlyscore_ruby/models/transactions_category_patch_element'
require 'friendlyscore_ruby/models/user'
require 'friendlyscore_ruby/models/user_collection'
require 'friendlyscore_ruby/models/user_reference_with_entity_type'

# APIs
require 'friendlyscore_ruby/api/auth_and_registration_api'
require 'friendlyscore_ruby/api/banking_data_api'
require 'friendlyscore_ruby/api/data_input_api'
require 'friendlyscore_ruby/api/invitation_api'
require 'friendlyscore_ruby/api/reports_api'
require 'friendlyscore_ruby/api/users_api'
require 'friendlyscore_ruby/api/util_api'

module FriendlyscoreClient
  class << self
    # Customize default settings for the SDK using block.
    #   FriendlyscoreClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
